# Generated by Django 5.1.6 on 2025-02-07 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('isOnline', models.BooleanField(default=False)),
                ('organizerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
