# Generated by Django 5.1.6 on 2025-02-08 04:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('the_wall', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalevent',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 9)),
        ),
        migrations.CreateModel(
            name='GlobalEventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_wall.globalevent')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.tag')),
            ],
            options={
                'unique_together': {('eventId', 'tagId')},
            },
        ),
        migrations.CreateModel(
            name='UserInterestTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.tag')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userId', 'tagId')},
            },
        ),
    ]
